site_name: GarGon-Dev
site_url: https://mydomain.org/mysite
theme:
  name: material
  icon:
    logo: material/garage-open-variant
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.indexes

  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: indigo

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
  - tags:
      enabled: true
      tags: true
      tags_file: blog/tags.md

nav:
  - About-me: index.md
  - Blog:
      - blog/index.md
      - blog/tags.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gargondev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/heliezer-garcia/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
